const mongoose = require('mongoose');

const shopifyOrderSchema = new mongoose.Schema({
    _id: { type: String },
    email: String,
    closed_at: Date,
    created_at: Date,
    updated_at: Date,
    number: Number,
    note: String,
    token: String,
    gateway: String,
    test: Boolean,
    total_price: String,
    subtotal_price: String,
    total_weight: Number,
    total_tax: String,
    taxes_included: Boolean,
    currency: String,
    financial_status: String,
    confirmed: Boolean,
    total_discounts: String,
    buyer_accepts_marketing: Boolean,
    name: String,
    referring_site: String,
    landing_site: String,
    cancelled_at: Date,
    cancel_reason: String,
    reference: String,
    user_id: String,
    location_id: String,
    source_identifier: String,
    source_url: String,
    device_id: String,
    phone: String,
    customer_locale: String,
    app_id: Number,
    browser_ip: String,
    landing_site_ref: String,
    order_number: String,
    discount_applications: Array,
    discount_codes: Array,
    note_attributes: Array,
    payment_gateway_names: Array,
    processing_method: String,
    source_name: String,
    fulfillment_status: String,
    tax_lines: Array,
    tags: String,
    contact_email: String,
    order_status_url: String,
    presentment_currency: String,
    total_line_items_price_set: Object,
    total_discounts_set: Object,
    total_shipping_price_set: Object,
    subtotal_price_set: Object,
    total_price_set: Object,
    total_tax_set: Object,
    line_items: Array,
    shipping_lines: Array,
    billing_address: Object,
    shipping_address: Object,
    fulfillments: Array,
    client_details: Object,
    refunds: Array,
    customer: Object,
});

module.exports = mongoose.model('ShopifyOrder', shopifyOrderSchema);
